readme.md
Love your guide - thanks for making it! I made some grammar and spelling fixes for readability.
=> Fix grammar/spelling

readme.md
The sentence is clearer now I think.
I admit, it is also an excuse to make my first "real" pull request and learning git/GitHub ! Hope I didn't mess anything...
🍻
=> Changed wrong word, removed unnecessary one

readme.md
Both prototype-based and class-based languages can use object-oriented design. The difference is in implementation.
JavaScript is perfectly capable of OOP, just as it is also capable of functional programming.
However, yes, the *class* sugar in JavaScript does not work in the same way as classes in class-based languages. This is because prototype-based and class-based languages have different inheritance models.
=> Fixed inheritance model language

readme.md
You may also want to consider discussing hoisting: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/var#var_hoisting
=> Update information about top scope declared var

readme.md
recommand -> recommend 
respectivly -> respectively
=> corrected typos

readme.md
This PR fixes a lot of grammatical mistakes. Thanks for writing this guide. I'd suggest adding an MIT license to the repo.
=> IMPROVE: Featured Image — Grammar, TitleCase, etc.

readme.md
=> Add details about async-await 

readme.md
Here 'block scoped' should be 'function scoped'
=> 'block scoped' should be 'function scoped'

readme.md
=> Fixed FR locale for mozilla developer page

readme.md
=> Fold detailed explanations

README.md
Minor bugfixes and clarifications
=> Clarifications in the async / await section

README.md
resolves #55, I approached this problem by seeing comparing the rest of the guide, and attempting to match the style. I agreed with @avimar that this duplicate links were probably not needed.
=> removed duplicate links and reworded as needed

translations/zh-CN.md
update the chinse version of cheatsheet
=> update chinese version

README.md
Correctly, it should say
> it gets easier
or
> things get easier
so I fixed it
=> Fix small typo (gets -> get)

README.md
* Improve the wording
* Separate implicit and explicit examples 
* Add an example for when implicit return doesn't work.
Probably closes #76.
=> Improve the explicit/implicit return section

README.md
https://github.com/mbeaudru/modern-js-cheatsheet/issues/27
=> Added a section for Anamorphisms, Catamorphisms, and Generators

README.md
Hi, Im adding a caution about difference of casting and comparing value. This is easy to mistake about how object compare to boolean value one.
=> Add comparing object value to boolean in Truthy/Falsy section.

translations/pl_PL.md
Hi, I've finished the Polish translation.
=> Polish translation (#90)

translations/pl_PL.md
The link from the table of contents did not work.
=> improve polish translations - fix Table of Contents links

translations/ja-JP.md
@mbeaudru It's late but I'd like to add Japanese translation if you don't mind.
If I miss anything important to make a PR for translation, please let me know. Thank you in advance :)
=> Add ja-JP translation.

README.md
Change one sentence for what I think is the correct form (would be great if a native speaker could confirm or inform that).
Change some code samples to get a uniform indentation style.
=> Small typo and indentation fixes

README.md
Added Array.prototype.find along with map, reduce and filter under array methods.
=> Add Array.prototype.find
